apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/namespace.yaml
  - ../../base/postgres/statefulset.yaml
  - ../../base/postgres/service.yaml
  - ../../base/postgres/pvc.yaml
  - ../../base/postgres/secret.yaml
  - ../../base/api/deployment.yaml
  - ../../base/api/service.yaml
  - ../../base/api/ingress.yaml
  - ../../base/api/hpa.yaml
